vestuarioWEB/Models/ErrorViewModel.cs
using System;

namespace vestuarioWEB.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

vestuarioWEB/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using vestuarioWEB.Models;

namespace vestuarioWEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

vestuarioWEB/Controllers/cadastrosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace vestuarioWEB.Controllers
{
    public class cadastrosController : Controller
    {
        public IActionResult Categorias()
        {
            return View();
        }

        public IActionResult Marcas()
        {
            return View();
        }
    }
}

vestuarioWEB/Controllers/listaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace vestuarioWEB.Controllers
{
    public class listaController : Controller
    {
        public IActionResult listaCategorias()
        {
            return View();
        }
        public IActionResult listaMarcas()
        {
            return View();
        }
    }
}

vestuarioWEB/Views/Cadastros/Categorias.cshtml
@{
    ViewData["Title"] = "Cadastro de Categorias | VestWEB";
}

<link href="~/css/cadastros.css" rel="stylesheet" type="text/css" media="all" />

<div id="pageintro" class="hoc clear">
    <!-- ################################################################################################ -->
    <article>
        <p>- Cadastro -</p>
        <h3 class="heading">CATEGORIAS</h3>
        <p>Categorias registradas na plataforma: <a asp-controller="lista" asp-action="listaCategorias">Clique aqui para acessar a lista</a></p>
    </article>
    <!-- ################################################################################################ -->
</div>

<div class="wrapper row3">
    <main class="hoc container clear">
        @*<section id="introblocks">
            <ul class="nospace group">
                <li class="one_third">
                    <figure>
                        <a class="imgover" href="#"><img src="images/demo/348x220.png" alt=""></a>
                        <figcaption>
                            <h6 class="heading">Aliquam faucibus</h6>
                            <p>Ipsum eu ipsum donec ac orci sed lectus elementum fringilla nullam dictum nisi nec mauris phasellus ut lacus.</p>
                        </figcaption>
                    </figure>
                </li>
            </ul>
        </section>*@
        <form>
            <div class="form-group">
                <label for="Campoidentificador">Identificador da Categoria</label>
                <input type="number" placeholder="ID" class="form-control" id="Campoidentificador" readonly>
            </div>
            <div class="form-group">
                <label for="desccategoria">Descrição da categoria</label>
                <input type="text" placeholder="categoria" class="form-control" id="desccategoria">
            </div>
            <button type="button" class="btn btn-primary">Salvar</button>
        </form>
    </main>
</div>

vestuarioWEB/Views/Cadastros/Marcas.cshtml
@{
    ViewData["Title"] = "Cadastro de Marcas - VestWEB";
}

<link href="~/css/cadastros.css" rel="stylesheet" type="text/css" media="all" />

<div id="pageintro" class="hoc clear">
    <!-- ################################################################################################ -->
    <article>
        <p>- Cadastro -</p>
        <h3 class="heading">MARCAS</h3>
        <p>Marcas registradas na plataforma: <a href="#">Clique aqui para acessar a lista</a></p>
    </article>
    <!-- ################################################################################################ -->
</div>

<div class="wrapper row3">
    <main class="hoc container clear">
        <form>
            <div class="form-group">
                <label for="Campoidentificador">Identificador da Categoria</label>
                <input type="number" placeholder="ID" class="form-control" id="Campoidentificador" readonly>
            </div>
            <div class="form-group">
                <label for="descmarca">Descrição da marca</label>
                <input type="text" placeholder="marca" class="form-control" id="descmarca" maxlength="30">
            </div>
            <button type="button" class="btn btn-primary">Salvar</button>
        </form>
    </main>
</div>

vestuarioWEB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página inicial | VestWEB";
}

<div id="pageintro" class="hoc clear">
    <!-- ################################################################################################ -->
    <article>
        <p>Bem vindo ao VestWEB</p>
        <h3 class="heading">Projeto WEB para utilização API</h3>
        <p>Estamos fazendo testes de consumo de API</p>
    </article>
    <!-- ################################################################################################ -->
</div>

<div class="wrapper row3">
    <main class="hoc container clear">
        <section id="introblocks">
            <ul class="nospace group">
                <li class="one_third">
                    <figure>
                        <a class="imgover" href="#"><img src="images/demo/348x220.png" alt=""></a>
                        <figcaption>
                            <h6 class="heading">Aliquam faucibus</h6>
                            <p>Ipsum eu ipsum donec ac orci sed lectus elementum fringilla nullam dictum nisi nec mauris phasellus ut lacus.</p>
                        </figcaption>
                    </figure>
                </li>
            </ul>
        </section>
    </main>
</div>

vestuarioWEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--
Template Name: Foxclore
Author: <a href="https://www.os-templates.com/">OS Templates</a>
Author URI: https://www.os-templates.com/
Copyright: OS-Templates.com
Licence: Free to use under our free template licence terms
Licence URI: https://www.os-templates.com/template-terms
-->
<html lang="">
<!-- To declare your language - read more here: https://www.w3.org/International/questions/qa-html-language-declarations -->
<head>
<title>@ViewData["Title"]</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link href="~/css/layout.css" rel="stylesheet" type="text/css" media="all">
</head>
    <body id="top">
        <!-- ################################################################################################ -->
        <!-- ################################################################################################ -->
        <!-- ################################################################################################ -->
        <!-- Top Background Image Wrapper -->
        <div class="bgded overlay" style="background-image:url('../images/demo/backgrounds/01.png');">
            <!-- ################################################################################################ -->
            <header id="header" class="hoc clear">
                <!-- ################################################################################################ -->
                <div id="logo" class="one_quarter first">
                    <h1><a asp-controller="Home" asp-action="Index">VestWEB</a></h1>
                    <p>Projeto WEB Vestuário</p>
                </div>
                <div class="three_quarter">
                    <ul class="nospace clear">
                        <li class="one_third first">
                            <div class="block clear"><a href="#"><i class="fas fa-phone"></i></a> <span><strong>Faça uma ligação:</strong> (18) 3022-8557 </span></div>
                        </li>
                        <li class="one_third">
                            <div class="block clear"><a href="#"><i class="fas fa-envelope"></i></a> <span><strong>Email Suporte:</strong> suporte@toledoprudente.edu.br</span></div>
                        </li>
                        <li class="one_third">
                            <div class="block clear"><a href="#"><i class="fas fa-clock"></i></a> <span><strong> Seg a Sab:</strong> 08:00 as 18:00</span></div>
                        </li>
                    </ul>
                </div>
                <!-- ################################################################################################ -->
            </header>
            <!-- ################################################################################################ -->
            <!-- ################################################################################################ -->
            <!-- ################################################################################################ -->
            <section id="navwrapper" class="hoc clear">
                <!-- ################################################################################################ -->
                <nav id="mainav">
                    <ul class="clear">
                        <li class="active"><a asp-controller="Home" asp-action="Index">Página inicial</a></li>
                        <li>
                            <a class="drop" href="#">Cadastros</a>
                            <ul>
                                <li><a asp-controller="cadastros" asp-action="Categorias">Categorias</a></li>
                                <li><a asp-controller="cadastros" asp-action="Marcas">Marcas</a></li>
                            </ul>
                        </li>
                        @*<li>
                            <a class="drop" href="#">Dropdown</a>
                            <ul>
                                <li><a href="#">Level 2</a></li>
                                <li>
                                    <a class="drop" href="#">Level 2 + Drop</a>
                                    <ul>
                                        <li><a href="#">Level 3</a></li>
                                        <li><a href="#">Level 3</a></li>
                                        <li><a href="#">Level 3</a></li>
                                    </ul>
                                </li>
                                <li><a href="#">Level 2</a></li>
                            </ul>
                        </li>*@
                    </ul>
                </nav>
            </section>
            @RenderBody()
        </div>

            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            @await RenderSectionAsync("Scripts", required: false)

    </body>
</html>

vestuarioWEB/Views/lista/listaCategorias.cshtml
@{
    ViewData["Title"] = "Lista de categorias | VestWEB";
}

<link href="~/css/cadastros.css" rel="stylesheet" type="text/css" media="all" />

<div id="pageintro" class="hoc clear">
    <!-- ################################################################################################ -->
    <article>
        <p>- Lista -</p>
        <h3 class="heading">CATEGORIAS</h3>
        <p>Para cadastrar uma categoria: <a asp-controller="cadastros" asp-action="Categorias">Clique aqui para acessar a tela cadastro</a></p>
    </article>
    <!-- ################################################################################################ -->
</div>

<div>
    <div>
        <label for="txtdescricaocategoria">Informe a descrição da categoria</label>
        <input type="text" class="form-control" id="txtdescricaocategoria" />
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Descrição</th>
                <th scope="col">Alterar</th>
                <th scope="col">Excluir</th>
            </tr>
        </thead>
        <tbody id="itens">
        </tbody>
    </table>
</div>

vestuarioWEB/Views/lista/listaMarcas.cshtml
@{
    ViewData["Title"] = "Lista de marcas | VestWEB";
}

<link href="~/css/cadastros.css" rel="stylesheet" type="text/css" media="all" />

<div id="pageintro" class="hoc clear">
    <!-- ################################################################################################ -->
    <article>
        <p>- Lista -</p>
        <h3 class="heading">MARCAS</h3>
        <p>Para cadastrar uma marca: <a asp-controller="cadastros" asp-action="marcas">Clique aqui para acessar a tela cadastro</a></p>
    </article>
    <!-- ################################################################################################ -->
</div>

<div class="wrapper row3">
    <main class="hoc container clear">
        <div class="form-group">
            <label for="txtdescricaocategoria">Informe a descrição da marca</label>
            <input type="text" class="form-control" id="txtdescricaomarca" />
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Descrição</th>
                    <th scope="col">Alterar</th>
                    <th scope="col">Excluir</th>
                </tr>
            </thead>
            <tbody id="itens">
            </tbody>
        </table>
    </main>
</div>